/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountDetails {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "integration", skip_serializing_if = "Option::is_none")]
    pub integration: Option<String>,
    #[serde(rename = "integration_slug", skip_serializing_if = "Option::is_none")]
    pub integration_slug: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::CategoryEnum>>,
    #[serde(rename = "end_user_origin_id", skip_serializing_if = "Option::is_none")]
    pub end_user_origin_id: Option<String>,
    #[serde(rename = "end_user_organization_name", skip_serializing_if = "Option::is_none")]
    pub end_user_organization_name: Option<String>,
    #[serde(rename = "end_user_email_address", skip_serializing_if = "Option::is_none")]
    pub end_user_email_address: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "webhook_listener_url", skip_serializing_if = "Option::is_none")]
    pub webhook_listener_url: Option<String>,
    /// Whether a Production Linked Account's credentials match another existing Production Linked Account. This field is `null` for Test Linked Accounts, incomplete Production Linked Accounts, and ignored duplicate Production Linked Account sets.
    #[serde(rename = "is_duplicate", skip_serializing_if = "Option::is_none")]
    pub is_duplicate: Option<bool>,
}

impl AccountDetails {
    pub fn new() -> AccountDetails {
        AccountDetails {
            id: None,
            integration: None,
            integration_slug: None,
            category: None,
            end_user_origin_id: None,
            end_user_organization_name: None,
            end_user_email_address: None,
            status: None,
            webhook_listener_url: None,
            is_duplicate: None,
        }
    }
}


