/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */

/// AccountDetailsAndActions : # The LinkedAccount Object ### Description The `LinkedAccount` object is used to represent an end user's link with a specific integration.  ### Usage Example View a list of your organization's `LinkedAccount` objects.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountDetailsAndActions {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<crate::models::CategoryEnum>>,
    #[serde(rename = "status")]
    pub status: Option<Box<crate::models::AccountDetailsAndActionsStatusEnum>>,
    #[serde(rename = "status_detail", skip_serializing_if = "Option::is_none")]
    pub status_detail: Option<String>,
    #[serde(rename = "end_user_origin_id", skip_serializing_if = "Option::is_none")]
    pub end_user_origin_id: Option<String>,
    #[serde(rename = "end_user_organization_name")]
    pub end_user_organization_name: String,
    #[serde(rename = "end_user_email_address")]
    pub end_user_email_address: String,
    #[serde(rename = "webhook_listener_url")]
    pub webhook_listener_url: String,
    /// Whether a Production Linked Account's credentials match another existing Production Linked Account. This field is `null` for Test Linked Accounts, incomplete Production Linked Accounts, and ignored duplicate Production Linked Account sets.
    #[serde(rename = "is_duplicate", skip_serializing_if = "Option::is_none")]
    pub is_duplicate: Option<bool>,
    #[serde(rename = "integration", skip_serializing_if = "Option::is_none")]
    pub integration: Option<Box<crate::models::AccountDetailsAndActionsIntegration>>,
}

impl AccountDetailsAndActions {
    /// # The LinkedAccount Object ### Description The `LinkedAccount` object is used to represent an end user's link with a specific integration.  ### Usage Example View a list of your organization's `LinkedAccount` objects.
    pub fn new(id: String, status: Option<crate::models::AccountDetailsAndActionsStatusEnum>, end_user_organization_name: String, end_user_email_address: String, webhook_listener_url: String) -> AccountDetailsAndActions {
        AccountDetailsAndActions {
            id,
            category: None,
            status: Box::new(status),
            status_detail: None,
            end_user_origin_id: None,
            end_user_organization_name,
            end_user_email_address,
            webhook_listener_url,
            is_duplicate: None,
            integration: None,
        }
    }
}


