/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CountryEnum {
    #[serde(rename = "AF")]
    AF,
    #[serde(rename = "AX")]
    AX,
    #[serde(rename = "AL")]
    AL,
    #[serde(rename = "DZ")]
    DZ,
    #[serde(rename = "AS")]
    _AS,
    #[serde(rename = "AD")]
    AD,
    #[serde(rename = "AO")]
    AO,
    #[serde(rename = "AI")]
    AI,
    #[serde(rename = "AQ")]
    AQ,
    #[serde(rename = "AG")]
    AG,
    #[serde(rename = "AR")]
    AR,
    #[serde(rename = "AM")]
    AM,
    #[serde(rename = "AW")]
    AW,
    #[serde(rename = "AU")]
    AU,
    #[serde(rename = "AT")]
    AT,
    #[serde(rename = "AZ")]
    AZ,
    #[serde(rename = "BS")]
    BS,
    #[serde(rename = "BH")]
    BH,
    #[serde(rename = "BD")]
    BD,
    #[serde(rename = "BB")]
    BB,
    #[serde(rename = "BY")]
    BY,
    #[serde(rename = "BE")]
    BE,
    #[serde(rename = "BZ")]
    BZ,
    #[serde(rename = "BJ")]
    BJ,
    #[serde(rename = "BM")]
    BM,
    #[serde(rename = "BT")]
    BT,
    #[serde(rename = "BO")]
    BO,
    #[serde(rename = "BQ")]
    BQ,
    #[serde(rename = "BA")]
    BA,
    #[serde(rename = "BW")]
    BW,
    #[serde(rename = "BV")]
    BV,
    #[serde(rename = "BR")]
    BR,
    #[serde(rename = "IO")]
    IO,
    #[serde(rename = "BN")]
    BN,
    #[serde(rename = "BG")]
    BG,
    #[serde(rename = "BF")]
    BF,
    #[serde(rename = "BI")]
    BI,
    #[serde(rename = "CV")]
    CV,
    #[serde(rename = "KH")]
    KH,
    #[serde(rename = "CM")]
    CM,
    #[serde(rename = "CA")]
    CA,
    #[serde(rename = "KY")]
    KY,
    #[serde(rename = "CF")]
    CF,
    #[serde(rename = "TD")]
    TD,
    #[serde(rename = "CL")]
    CL,
    #[serde(rename = "CN")]
    CN,
    #[serde(rename = "CX")]
    CX,
    #[serde(rename = "CC")]
    CC,
    #[serde(rename = "CO")]
    CO,
    #[serde(rename = "KM")]
    KM,
    #[serde(rename = "CG")]
    CG,
    #[serde(rename = "CD")]
    CD,
    #[serde(rename = "CK")]
    CK,
    #[serde(rename = "CR")]
    CR,
    #[serde(rename = "CI")]
    CI,
    #[serde(rename = "HR")]
    HR,
    #[serde(rename = "CU")]
    CU,
    #[serde(rename = "CW")]
    CW,
    #[serde(rename = "CY")]
    CY,
    #[serde(rename = "CZ")]
    CZ,
    #[serde(rename = "DK")]
    DK,
    #[serde(rename = "DJ")]
    DJ,
    #[serde(rename = "DM")]
    DM,
    #[serde(rename = "DO")]
    _DO,
    #[serde(rename = "EC")]
    EC,
    #[serde(rename = "EG")]
    EG,
    #[serde(rename = "SV")]
    SV,
    #[serde(rename = "GQ")]
    GQ,
    #[serde(rename = "ER")]
    ER,
    #[serde(rename = "EE")]
    EE,
    #[serde(rename = "SZ")]
    SZ,
    #[serde(rename = "ET")]
    ET,
    #[serde(rename = "FK")]
    FK,
    #[serde(rename = "FO")]
    FO,
    #[serde(rename = "FJ")]
    FJ,
    #[serde(rename = "FI")]
    FI,
    #[serde(rename = "FR")]
    FR,
    #[serde(rename = "GF")]
    GF,
    #[serde(rename = "PF")]
    PF,
    #[serde(rename = "TF")]
    TF,
    #[serde(rename = "GA")]
    GA,
    #[serde(rename = "GM")]
    GM,
    #[serde(rename = "GE")]
    GE,
    #[serde(rename = "DE")]
    DE,
    #[serde(rename = "GH")]
    GH,
    #[serde(rename = "GI")]
    GI,
    #[serde(rename = "GR")]
    GR,
    #[serde(rename = "GL")]
    GL,
    #[serde(rename = "GD")]
    GD,
    #[serde(rename = "GP")]
    GP,
    #[serde(rename = "GU")]
    GU,
    #[serde(rename = "GT")]
    GT,
    #[serde(rename = "GG")]
    GG,
    #[serde(rename = "GN")]
    GN,
    #[serde(rename = "GW")]
    GW,
    #[serde(rename = "GY")]
    GY,
    #[serde(rename = "HT")]
    HT,
    #[serde(rename = "HM")]
    HM,
    #[serde(rename = "VA")]
    VA,
    #[serde(rename = "HN")]
    HN,
    #[serde(rename = "HK")]
    HK,
    #[serde(rename = "HU")]
    HU,
    #[serde(rename = "IS")]
    IS,
    #[serde(rename = "IN")]
    _IN,
    #[serde(rename = "ID")]
    ID,
    #[serde(rename = "IR")]
    IR,
    #[serde(rename = "IQ")]
    IQ,
    #[serde(rename = "IE")]
    IE,
    #[serde(rename = "IM")]
    IM,
    #[serde(rename = "IL")]
    IL,
    #[serde(rename = "IT")]
    IT,
    #[serde(rename = "JM")]
    JM,
    #[serde(rename = "JP")]
    JP,
    #[serde(rename = "JE")]
    JE,
    #[serde(rename = "JO")]
    JO,
    #[serde(rename = "KZ")]
    KZ,
    #[serde(rename = "KE")]
    KE,
    #[serde(rename = "KI")]
    KI,
    #[serde(rename = "KW")]
    KW,
    #[serde(rename = "KG")]
    KG,
    #[serde(rename = "LA")]
    LA,
    #[serde(rename = "LV")]
    LV,
    #[serde(rename = "LB")]
    LB,
    #[serde(rename = "LS")]
    LS,
    #[serde(rename = "LR")]
    LR,
    #[serde(rename = "LY")]
    LY,
    #[serde(rename = "LI")]
    LI,
    #[serde(rename = "LT")]
    LT,
    #[serde(rename = "LU")]
    LU,
    #[serde(rename = "MO")]
    MO,
    #[serde(rename = "MG")]
    MG,
    #[serde(rename = "MW")]
    MW,
    #[serde(rename = "MY")]
    MY,
    #[serde(rename = "MV")]
    MV,
    #[serde(rename = "ML")]
    ML,
    #[serde(rename = "MT")]
    MT,
    #[serde(rename = "MH")]
    MH,
    #[serde(rename = "MQ")]
    MQ,
    #[serde(rename = "MR")]
    MR,
    #[serde(rename = "MU")]
    MU,
    #[serde(rename = "YT")]
    YT,
    #[serde(rename = "MX")]
    MX,
    #[serde(rename = "FM")]
    FM,
    #[serde(rename = "MD")]
    MD,
    #[serde(rename = "MC")]
    MC,
    #[serde(rename = "MN")]
    MN,
    #[serde(rename = "ME")]
    ME,
    #[serde(rename = "MS")]
    MS,
    #[serde(rename = "MA")]
    MA,
    #[serde(rename = "MZ")]
    MZ,
    #[serde(rename = "MM")]
    MM,
    #[serde(rename = "NA")]
    NA,
    #[serde(rename = "NR")]
    NR,
    #[serde(rename = "NP")]
    NP,
    #[serde(rename = "NL")]
    NL,
    #[serde(rename = "NC")]
    NC,
    #[serde(rename = "NZ")]
    NZ,
    #[serde(rename = "NI")]
    NI,
    #[serde(rename = "NE")]
    NE,
    #[serde(rename = "NG")]
    NG,
    #[serde(rename = "NU")]
    NU,
    #[serde(rename = "NF")]
    NF,
    #[serde(rename = "KP")]
    KP,
    #[serde(rename = "MK")]
    MK,
    #[serde(rename = "MP")]
    MP,
    #[serde(rename = "NO")]
    NO,
    #[serde(rename = "OM")]
    OM,
    #[serde(rename = "PK")]
    PK,
    #[serde(rename = "PW")]
    PW,
    #[serde(rename = "PS")]
    PS,
    #[serde(rename = "PA")]
    PA,
    #[serde(rename = "PG")]
    PG,
    #[serde(rename = "PY")]
    PY,
    #[serde(rename = "PE")]
    PE,
    #[serde(rename = "PH")]
    PH,
    #[serde(rename = "PN")]
    PN,
    #[serde(rename = "PL")]
    PL,
    #[serde(rename = "PT")]
    PT,
    #[serde(rename = "PR")]
    PR,
    #[serde(rename = "QA")]
    QA,
    #[serde(rename = "RE")]
    RE,
    #[serde(rename = "RO")]
    RO,
    #[serde(rename = "RU")]
    RU,
    #[serde(rename = "RW")]
    RW,
    #[serde(rename = "BL")]
    BL,
    #[serde(rename = "SH")]
    SH,
    #[serde(rename = "KN")]
    KN,
    #[serde(rename = "LC")]
    LC,
    #[serde(rename = "MF")]
    MF,
    #[serde(rename = "PM")]
    PM,
    #[serde(rename = "VC")]
    VC,
    #[serde(rename = "WS")]
    WS,
    #[serde(rename = "SM")]
    SM,
    #[serde(rename = "ST")]
    ST,
    #[serde(rename = "SA")]
    SA,
    #[serde(rename = "SN")]
    SN,
    #[serde(rename = "RS")]
    RS,
    #[serde(rename = "SC")]
    SC,
    #[serde(rename = "SL")]
    SL,
    #[serde(rename = "SG")]
    SG,
    #[serde(rename = "SX")]
    SX,
    #[serde(rename = "SK")]
    SK,
    #[serde(rename = "SI")]
    SI,
    #[serde(rename = "SB")]
    SB,
    #[serde(rename = "SO")]
    SO,
    #[serde(rename = "ZA")]
    ZA,
    #[serde(rename = "GS")]
    GS,
    #[serde(rename = "KR")]
    KR,
    #[serde(rename = "SS")]
    SS,
    #[serde(rename = "ES")]
    ES,
    #[serde(rename = "LK")]
    LK,
    #[serde(rename = "SD")]
    SD,
    #[serde(rename = "SR")]
    SR,
    #[serde(rename = "SJ")]
    SJ,
    #[serde(rename = "SE")]
    SE,
    #[serde(rename = "CH")]
    CH,
    #[serde(rename = "SY")]
    SY,
    #[serde(rename = "TW")]
    TW,
    #[serde(rename = "TJ")]
    TJ,
    #[serde(rename = "TZ")]
    TZ,
    #[serde(rename = "TH")]
    TH,
    #[serde(rename = "TL")]
    TL,
    #[serde(rename = "TG")]
    TG,
    #[serde(rename = "TK")]
    TK,
    #[serde(rename = "TO")]
    TO,
    #[serde(rename = "TT")]
    TT,
    #[serde(rename = "TN")]
    TN,
    #[serde(rename = "TR")]
    TR,
    #[serde(rename = "TM")]
    TM,
    #[serde(rename = "TC")]
    TC,
    #[serde(rename = "TV")]
    TV,
    #[serde(rename = "UG")]
    UG,
    #[serde(rename = "UA")]
    UA,
    #[serde(rename = "AE")]
    AE,
    #[serde(rename = "GB")]
    GB,
    #[serde(rename = "UM")]
    UM,
    #[serde(rename = "US")]
    US,
    #[serde(rename = "UY")]
    UY,
    #[serde(rename = "UZ")]
    UZ,
    #[serde(rename = "VU")]
    VU,
    #[serde(rename = "VE")]
    VE,
    #[serde(rename = "VN")]
    VN,
    #[serde(rename = "VG")]
    VG,
    #[serde(rename = "VI")]
    VI,
    #[serde(rename = "WF")]
    WF,
    #[serde(rename = "EH")]
    EH,
    #[serde(rename = "YE")]
    YE,
    #[serde(rename = "ZM")]
    ZM,
    #[serde(rename = "ZW")]
    ZW,

}

impl ToString for CountryEnum {
    fn to_string(&self) -> String {
        match self {
            Self::AF => String::from("AF"),
            Self::AX => String::from("AX"),
            Self::AL => String::from("AL"),
            Self::DZ => String::from("DZ"),
            Self::_AS => String::from("AS"),
            Self::AD => String::from("AD"),
            Self::AO => String::from("AO"),
            Self::AI => String::from("AI"),
            Self::AQ => String::from("AQ"),
            Self::AG => String::from("AG"),
            Self::AR => String::from("AR"),
            Self::AM => String::from("AM"),
            Self::AW => String::from("AW"),
            Self::AU => String::from("AU"),
            Self::AT => String::from("AT"),
            Self::AZ => String::from("AZ"),
            Self::BS => String::from("BS"),
            Self::BH => String::from("BH"),
            Self::BD => String::from("BD"),
            Self::BB => String::from("BB"),
            Self::BY => String::from("BY"),
            Self::BE => String::from("BE"),
            Self::BZ => String::from("BZ"),
            Self::BJ => String::from("BJ"),
            Self::BM => String::from("BM"),
            Self::BT => String::from("BT"),
            Self::BO => String::from("BO"),
            Self::BQ => String::from("BQ"),
            Self::BA => String::from("BA"),
            Self::BW => String::from("BW"),
            Self::BV => String::from("BV"),
            Self::BR => String::from("BR"),
            Self::IO => String::from("IO"),
            Self::BN => String::from("BN"),
            Self::BG => String::from("BG"),
            Self::BF => String::from("BF"),
            Self::BI => String::from("BI"),
            Self::CV => String::from("CV"),
            Self::KH => String::from("KH"),
            Self::CM => String::from("CM"),
            Self::CA => String::from("CA"),
            Self::KY => String::from("KY"),
            Self::CF => String::from("CF"),
            Self::TD => String::from("TD"),
            Self::CL => String::from("CL"),
            Self::CN => String::from("CN"),
            Self::CX => String::from("CX"),
            Self::CC => String::from("CC"),
            Self::CO => String::from("CO"),
            Self::KM => String::from("KM"),
            Self::CG => String::from("CG"),
            Self::CD => String::from("CD"),
            Self::CK => String::from("CK"),
            Self::CR => String::from("CR"),
            Self::CI => String::from("CI"),
            Self::HR => String::from("HR"),
            Self::CU => String::from("CU"),
            Self::CW => String::from("CW"),
            Self::CY => String::from("CY"),
            Self::CZ => String::from("CZ"),
            Self::DK => String::from("DK"),
            Self::DJ => String::from("DJ"),
            Self::DM => String::from("DM"),
            Self::_DO => String::from("DO"),
            Self::EC => String::from("EC"),
            Self::EG => String::from("EG"),
            Self::SV => String::from("SV"),
            Self::GQ => String::from("GQ"),
            Self::ER => String::from("ER"),
            Self::EE => String::from("EE"),
            Self::SZ => String::from("SZ"),
            Self::ET => String::from("ET"),
            Self::FK => String::from("FK"),
            Self::FO => String::from("FO"),
            Self::FJ => String::from("FJ"),
            Self::FI => String::from("FI"),
            Self::FR => String::from("FR"),
            Self::GF => String::from("GF"),
            Self::PF => String::from("PF"),
            Self::TF => String::from("TF"),
            Self::GA => String::from("GA"),
            Self::GM => String::from("GM"),
            Self::GE => String::from("GE"),
            Self::DE => String::from("DE"),
            Self::GH => String::from("GH"),
            Self::GI => String::from("GI"),
            Self::GR => String::from("GR"),
            Self::GL => String::from("GL"),
            Self::GD => String::from("GD"),
            Self::GP => String::from("GP"),
            Self::GU => String::from("GU"),
            Self::GT => String::from("GT"),
            Self::GG => String::from("GG"),
            Self::GN => String::from("GN"),
            Self::GW => String::from("GW"),
            Self::GY => String::from("GY"),
            Self::HT => String::from("HT"),
            Self::HM => String::from("HM"),
            Self::VA => String::from("VA"),
            Self::HN => String::from("HN"),
            Self::HK => String::from("HK"),
            Self::HU => String::from("HU"),
            Self::IS => String::from("IS"),
            Self::_IN => String::from("IN"),
            Self::ID => String::from("ID"),
            Self::IR => String::from("IR"),
            Self::IQ => String::from("IQ"),
            Self::IE => String::from("IE"),
            Self::IM => String::from("IM"),
            Self::IL => String::from("IL"),
            Self::IT => String::from("IT"),
            Self::JM => String::from("JM"),
            Self::JP => String::from("JP"),
            Self::JE => String::from("JE"),
            Self::JO => String::from("JO"),
            Self::KZ => String::from("KZ"),
            Self::KE => String::from("KE"),
            Self::KI => String::from("KI"),
            Self::KW => String::from("KW"),
            Self::KG => String::from("KG"),
            Self::LA => String::from("LA"),
            Self::LV => String::from("LV"),
            Self::LB => String::from("LB"),
            Self::LS => String::from("LS"),
            Self::LR => String::from("LR"),
            Self::LY => String::from("LY"),
            Self::LI => String::from("LI"),
            Self::LT => String::from("LT"),
            Self::LU => String::from("LU"),
            Self::MO => String::from("MO"),
            Self::MG => String::from("MG"),
            Self::MW => String::from("MW"),
            Self::MY => String::from("MY"),
            Self::MV => String::from("MV"),
            Self::ML => String::from("ML"),
            Self::MT => String::from("MT"),
            Self::MH => String::from("MH"),
            Self::MQ => String::from("MQ"),
            Self::MR => String::from("MR"),
            Self::MU => String::from("MU"),
            Self::YT => String::from("YT"),
            Self::MX => String::from("MX"),
            Self::FM => String::from("FM"),
            Self::MD => String::from("MD"),
            Self::MC => String::from("MC"),
            Self::MN => String::from("MN"),
            Self::ME => String::from("ME"),
            Self::MS => String::from("MS"),
            Self::MA => String::from("MA"),
            Self::MZ => String::from("MZ"),
            Self::MM => String::from("MM"),
            Self::NA => String::from("NA"),
            Self::NR => String::from("NR"),
            Self::NP => String::from("NP"),
            Self::NL => String::from("NL"),
            Self::NC => String::from("NC"),
            Self::NZ => String::from("NZ"),
            Self::NI => String::from("NI"),
            Self::NE => String::from("NE"),
            Self::NG => String::from("NG"),
            Self::NU => String::from("NU"),
            Self::NF => String::from("NF"),
            Self::KP => String::from("KP"),
            Self::MK => String::from("MK"),
            Self::MP => String::from("MP"),
            Self::NO => String::from("NO"),
            Self::OM => String::from("OM"),
            Self::PK => String::from("PK"),
            Self::PW => String::from("PW"),
            Self::PS => String::from("PS"),
            Self::PA => String::from("PA"),
            Self::PG => String::from("PG"),
            Self::PY => String::from("PY"),
            Self::PE => String::from("PE"),
            Self::PH => String::from("PH"),
            Self::PN => String::from("PN"),
            Self::PL => String::from("PL"),
            Self::PT => String::from("PT"),
            Self::PR => String::from("PR"),
            Self::QA => String::from("QA"),
            Self::RE => String::from("RE"),
            Self::RO => String::from("RO"),
            Self::RU => String::from("RU"),
            Self::RW => String::from("RW"),
            Self::BL => String::from("BL"),
            Self::SH => String::from("SH"),
            Self::KN => String::from("KN"),
            Self::LC => String::from("LC"),
            Self::MF => String::from("MF"),
            Self::PM => String::from("PM"),
            Self::VC => String::from("VC"),
            Self::WS => String::from("WS"),
            Self::SM => String::from("SM"),
            Self::ST => String::from("ST"),
            Self::SA => String::from("SA"),
            Self::SN => String::from("SN"),
            Self::RS => String::from("RS"),
            Self::SC => String::from("SC"),
            Self::SL => String::from("SL"),
            Self::SG => String::from("SG"),
            Self::SX => String::from("SX"),
            Self::SK => String::from("SK"),
            Self::SI => String::from("SI"),
            Self::SB => String::from("SB"),
            Self::SO => String::from("SO"),
            Self::ZA => String::from("ZA"),
            Self::GS => String::from("GS"),
            Self::KR => String::from("KR"),
            Self::SS => String::from("SS"),
            Self::ES => String::from("ES"),
            Self::LK => String::from("LK"),
            Self::SD => String::from("SD"),
            Self::SR => String::from("SR"),
            Self::SJ => String::from("SJ"),
            Self::SE => String::from("SE"),
            Self::CH => String::from("CH"),
            Self::SY => String::from("SY"),
            Self::TW => String::from("TW"),
            Self::TJ => String::from("TJ"),
            Self::TZ => String::from("TZ"),
            Self::TH => String::from("TH"),
            Self::TL => String::from("TL"),
            Self::TG => String::from("TG"),
            Self::TK => String::from("TK"),
            Self::TO => String::from("TO"),
            Self::TT => String::from("TT"),
            Self::TN => String::from("TN"),
            Self::TR => String::from("TR"),
            Self::TM => String::from("TM"),
            Self::TC => String::from("TC"),
            Self::TV => String::from("TV"),
            Self::UG => String::from("UG"),
            Self::UA => String::from("UA"),
            Self::AE => String::from("AE"),
            Self::GB => String::from("GB"),
            Self::UM => String::from("UM"),
            Self::US => String::from("US"),
            Self::UY => String::from("UY"),
            Self::UZ => String::from("UZ"),
            Self::VU => String::from("VU"),
            Self::VE => String::from("VE"),
            Self::VN => String::from("VN"),
            Self::VG => String::from("VG"),
            Self::VI => String::from("VI"),
            Self::WF => String::from("WF"),
            Self::EH => String::from("EH"),
            Self::YE => String::from("YE"),
            Self::ZM => String::from("ZM"),
            Self::ZW => String::from("ZW"),
        }
    }
}

impl Default for CountryEnum {
    fn default() -> CountryEnum {
        Self::AF
    }
}




