/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DebugModelLogSummary {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl DebugModelLogSummary {
    pub fn new(url: String, method: String, status_code: i32) -> DebugModelLogSummary {
        DebugModelLogSummary {
            url,
            method,
            status_code,
        }
    }
}


