/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DebugModeLog {
    #[serde(rename = "log_id")]
    pub log_id: String,
    #[serde(rename = "dashboard_view")]
    pub dashboard_view: String,
    #[serde(rename = "log_summary")]
    pub log_summary: Box<crate::models::DebugModelLogSummary>,
}

impl DebugModeLog {
    pub fn new(log_id: String, dashboard_view: String, log_summary: crate::models::DebugModelLogSummary) -> DebugModeLog {
        DebugModeLog {
            log_id,
            dashboard_view,
            log_summary: Box::new(log_summary),
        }
    }
}


