/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EarningTypeEnum {
    #[serde(rename = "SALARY")]
    SALARY,
    #[serde(rename = "REIMBURSEMENT")]
    REIMBURSEMENT,
    #[serde(rename = "OVERTIME")]
    OVERTIME,
    #[serde(rename = "BONUS")]
    BONUS,

}

impl ToString for EarningTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::SALARY => String::from("SALARY"),
            Self::REIMBURSEMENT => String::from("REIMBURSEMENT"),
            Self::OVERTIME => String::from("OVERTIME"),
            Self::BONUS => String::from("BONUS"),
        }
    }
}

impl Default for EarningTypeEnum {
    fn default() -> EarningTypeEnum {
        Self::SALARY
    }
}




