/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmployeeEndpointRequest {
    #[serde(rename = "model")]
    pub model: Box<crate::models::EmployeeRequest>,
}

impl EmployeeEndpointRequest {
    pub fn new(model: crate::models::EmployeeRequest) -> EmployeeEndpointRequest {
        EmployeeEndpointRequest {
            model: Box::new(model),
        }
    }
}


