/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EmploymentStatusEnum {
    #[serde(rename = "ACTIVE")]
    ACTIVE,
    #[serde(rename = "PENDING")]
    PENDING,
    #[serde(rename = "INACTIVE")]
    INACTIVE,

}

impl ToString for EmploymentStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::ACTIVE => String::from("ACTIVE"),
            Self::PENDING => String::from("PENDING"),
            Self::INACTIVE => String::from("INACTIVE"),
        }
    }
}

impl Default for EmploymentStatusEnum {
    fn default() -> EmploymentStatusEnum {
        Self::ACTIVE
    }
}




