/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncodingEnum {
    #[serde(rename = "RAW")]
    RAW,
    #[serde(rename = "BASE64")]
    BASE64,
    #[serde(rename = "GZIP_BASE64")]
    GZIPBASE64,

}

impl ToString for EncodingEnum {
    fn to_string(&self) -> String {
        match self {
            Self::RAW => String::from("RAW"),
            Self::BASE64 => String::from("BASE64"),
            Self::GZIPBASE64 => String::from("GZIP_BASE64"),
        }
    }
}

impl Default for EncodingEnum {
    fn default() -> EncodingEnum {
        Self::RAW
    }
}




