/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EthnicityEnum {
    #[serde(rename = "AMERICAN_INDIAN_OR_ALASKA_NATIVE")]
    AMERICANINDIANORALASKANATIVE,
    #[serde(rename = "ASIAN_OR_INDIAN_SUBCONTINENT")]
    ASIANORINDIANSUBCONTINENT,
    #[serde(rename = "BLACK_OR_AFRICAN_AMERICAN")]
    BLACKORAFRICANAMERICAN,
    #[serde(rename = "HISPANIC_OR_LATINO")]
    HISPANICORLATINO,
    #[serde(rename = "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER")]
    NATIVEHAWAIIANOROTHERPACIFICISLANDER,
    #[serde(rename = "TWO_OR_MORE_RACES")]
    TWOORMORERACES,
    #[serde(rename = "WHITE")]
    WHITE,
    #[serde(rename = "PREFER_NOT_TO_DISCLOSE")]
    PREFERNOTTODISCLOSE,

}

impl ToString for EthnicityEnum {
    fn to_string(&self) -> String {
        match self {
            Self::AMERICANINDIANORALASKANATIVE => String::from("AMERICAN_INDIAN_OR_ALASKA_NATIVE"),
            Self::ASIANORINDIANSUBCONTINENT => String::from("ASIAN_OR_INDIAN_SUBCONTINENT"),
            Self::BLACKORAFRICANAMERICAN => String::from("BLACK_OR_AFRICAN_AMERICAN"),
            Self::HISPANICORLATINO => String::from("HISPANIC_OR_LATINO"),
            Self::NATIVEHAWAIIANOROTHERPACIFICISLANDER => String::from("NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER"),
            Self::TWOORMORERACES => String::from("TWO_OR_MORE_RACES"),
            Self::WHITE => String::from("WHITE"),
            Self::PREFERNOTTODISCLOSE => String::from("PREFER_NOT_TO_DISCLOSE"),
        }
    }
}

impl Default for EthnicityEnum {
    fn default() -> EthnicityEnum {
        Self::AMERICANINDIANORALASKANATIVE
    }
}




