/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FlsaStatusEnum {
    #[serde(rename = "EXEMPT")]
    EXEMPT,
    #[serde(rename = "SALARIED_NONEXEMPT")]
    SALARIEDNONEXEMPT,
    #[serde(rename = "NONEXEMPT")]
    NONEXEMPT,
    #[serde(rename = "OWNER")]
    OWNER,

}

impl ToString for FlsaStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::EXEMPT => String::from("EXEMPT"),
            Self::SALARIEDNONEXEMPT => String::from("SALARIED_NONEXEMPT"),
            Self::NONEXEMPT => String::from("NONEXEMPT"),
            Self::OWNER => String::from("OWNER"),
        }
    }
}

impl Default for FlsaStatusEnum {
    fn default() -> FlsaStatusEnum {
        Self::EXEMPT
    }
}




