/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupTypeEnum {
    #[serde(rename = "TEAM")]
    TEAM,
    #[serde(rename = "DEPARTMENT")]
    DEPARTMENT,
    #[serde(rename = "COST_CENTER")]
    COSTCENTER,
    #[serde(rename = "BUSINESS_UNIT")]
    BUSINESSUNIT,

}

impl ToString for GroupTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::TEAM => String::from("TEAM"),
            Self::DEPARTMENT => String::from("DEPARTMENT"),
            Self::COSTCENTER => String::from("COST_CENTER"),
            Self::BUSINESSUNIT => String::from("BUSINESS_UNIT"),
        }
    }
}

impl Default for GroupTypeEnum {
    fn default() -> GroupTypeEnum {
        Self::TEAM
    }
}




