/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IgnoreCommonModel {
    #[serde(rename = "reason")]
    pub reason: Option<Box<crate::models::ReasonEnum>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl IgnoreCommonModel {
    pub fn new(reason: Option<crate::models::ReasonEnum>) -> IgnoreCommonModel {
        IgnoreCommonModel {
            reason: Box::new(reason),
            message: None,
        }
    }
}


