/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IssueStatusEnum {
    #[serde(rename = "ONGOING")]
    ONGOING,
    #[serde(rename = "RESOLVED")]
    RESOLVED,

}

impl ToString for IssueStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::ONGOING => String::from("ONGOING"),
            Self::RESOLVED => String::from("RESOLVED"),
        }
    }
}

impl Default for IssueStatusEnum {
    fn default() -> IssueStatusEnum {
        Self::ONGOING
    }
}




