/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkedAccountSelectiveSyncConfigurationRequest {
    /// The conditions belonging to a selective sync.
    #[serde(rename = "linked_account_conditions")]
    pub linked_account_conditions: Vec<crate::models::LinkedAccountConditionRequest>,
}

impl LinkedAccountSelectiveSyncConfigurationRequest {
    pub fn new(linked_account_conditions: Vec<crate::models::LinkedAccountConditionRequest>) -> LinkedAccountSelectiveSyncConfigurationRequest {
        LinkedAccountSelectiveSyncConfigurationRequest {
            linked_account_conditions,
        }
    }
}


