/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkToken {
    #[serde(rename = "link_token")]
    pub link_token: String,
    #[serde(rename = "integration_name")]
    pub integration_name: String,
    #[serde(rename = "magic_link_url", skip_serializing_if = "Option::is_none")]
    pub magic_link_url: Option<String>,
}

impl LinkToken {
    pub fn new(link_token: String, integration_name: String) -> LinkToken {
        LinkToken {
            link_token,
            integration_name,
            magic_link_url: None,
        }
    }
}


