/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkedAccountStatus {
    #[serde(rename = "linked_account_status")]
    pub linked_account_status: String,
    #[serde(rename = "can_make_request")]
    pub can_make_request: bool,
}

impl LinkedAccountStatus {
    pub fn new(linked_account_status: String, can_make_request: bool) -> LinkedAccountStatus {
        LinkedAccountStatus {
            linked_account_status,
            can_make_request,
        }
    }
}


