/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkedAccountSelectiveSyncConfiguration {
    /// The conditions belonging to a selective sync.
    #[serde(rename = "linked_account_conditions", skip_serializing_if = "Option::is_none")]
    pub linked_account_conditions: Option<Vec<crate::models::LinkedAccountCondition>>,
}

impl LinkedAccountSelectiveSyncConfiguration {
    pub fn new() -> LinkedAccountSelectiveSyncConfiguration {
        LinkedAccountSelectiveSyncConfiguration {
            linked_account_conditions: None,
        }
    }
}


