/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkedAccountSelectiveSyncConfigurationListRequest {
    /// The selective syncs associated with a linked account.
    #[serde(rename = "sync_configurations")]
    pub sync_configurations: Vec<crate::models::LinkedAccountSelectiveSyncConfigurationRequest>,
}

impl LinkedAccountSelectiveSyncConfigurationListRequest {
    pub fn new(sync_configurations: Vec<crate::models::LinkedAccountSelectiveSyncConfigurationRequest>) -> LinkedAccountSelectiveSyncConfigurationListRequest {
        LinkedAccountSelectiveSyncConfigurationListRequest {
            sync_configurations,
        }
    }
}


