/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LocationTypeEnum {
    #[serde(rename = "HOME")]
    HOME,
    #[serde(rename = "WORK")]
    WORK,

}

impl ToString for LocationTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::HOME => String::from("HOME"),
            Self::WORK => String::from("WORK"),
        }
    }
}

impl Default for LocationTypeEnum {
    fn default() -> LocationTypeEnum {
        Self::HOME
    }
}




