/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaritalStatusEnum {
    #[serde(rename = "SINGLE")]
    SINGLE,
    #[serde(rename = "MARRIED_FILING_JOINTLY")]
    MARRIEDFILINGJOINTLY,
    #[serde(rename = "MARRIED_FILING_SEPARATELY")]
    MARRIEDFILINGSEPARATELY,
    #[serde(rename = "HEAD_OF_HOUSEHOLD")]
    HEADOFHOUSEHOLD,
    #[serde(rename = "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD")]
    QUALIFYINGWIDOWORWIDOWERWITHDEPENDENTCHILD,

}

impl ToString for MaritalStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::SINGLE => String::from("SINGLE"),
            Self::MARRIEDFILINGJOINTLY => String::from("MARRIED_FILING_JOINTLY"),
            Self::MARRIEDFILINGSEPARATELY => String::from("MARRIED_FILING_SEPARATELY"),
            Self::HEADOFHOUSEHOLD => String::from("HEAD_OF_HOUSEHOLD"),
            Self::QUALIFYINGWIDOWORWIDOWERWITHDEPENDENTCHILD => String::from("QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD"),
        }
    }
}

impl Default for MaritalStatusEnum {
    fn default() -> MaritalStatusEnum {
        Self::SINGLE
    }
}




