/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MethodEnum {
    #[serde(rename = "GET")]
    GET,
    #[serde(rename = "OPTIONS")]
    OPTIONS,
    #[serde(rename = "HEAD")]
    HEAD,
    #[serde(rename = "POST")]
    POST,
    #[serde(rename = "PUT")]
    PUT,
    #[serde(rename = "PATCH")]
    PATCH,
    #[serde(rename = "DELETE")]
    DELETE,

}

impl ToString for MethodEnum {
    fn to_string(&self) -> String {
        match self {
            Self::GET => String::from("GET"),
            Self::OPTIONS => String::from("OPTIONS"),
            Self::HEAD => String::from("HEAD"),
            Self::POST => String::from("POST"),
            Self::PUT => String::from("PUT"),
            Self::PATCH => String::from("PATCH"),
            Self::DELETE => String::from("DELETE"),
        }
    }
}

impl Default for MethodEnum {
    fn default() -> MethodEnum {
        Self::GET
    }
}




