/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayCurrencyEnum {
    #[serde(rename = "XUA")]
    XUA,
    #[serde(rename = "AFN")]
    AFN,
    #[serde(rename = "AFA")]
    AFA,
    #[serde(rename = "ALL")]
    ALL,
    #[serde(rename = "ALK")]
    ALK,
    #[serde(rename = "DZD")]
    DZD,
    #[serde(rename = "ADP")]
    ADP,
    #[serde(rename = "AOA")]
    AOA,
    #[serde(rename = "AOK")]
    AOK,
    #[serde(rename = "AON")]
    AON,
    #[serde(rename = "AOR")]
    AOR,
    #[serde(rename = "ARA")]
    ARA,
    #[serde(rename = "ARS")]
    ARS,
    #[serde(rename = "ARM")]
    ARM,
    #[serde(rename = "ARP")]
    ARP,
    #[serde(rename = "ARL")]
    ARL,
    #[serde(rename = "AMD")]
    AMD,
    #[serde(rename = "AWG")]
    AWG,
    #[serde(rename = "AUD")]
    AUD,
    #[serde(rename = "ATS")]
    ATS,
    #[serde(rename = "AZN")]
    AZN,
    #[serde(rename = "AZM")]
    AZM,
    #[serde(rename = "BSD")]
    BSD,
    #[serde(rename = "BHD")]
    BHD,
    #[serde(rename = "BDT")]
    BDT,
    #[serde(rename = "BBD")]
    BBD,
    #[serde(rename = "BYN")]
    BYN,
    #[serde(rename = "BYB")]
    BYB,
    #[serde(rename = "BYR")]
    BYR,
    #[serde(rename = "BEF")]
    BEF,
    #[serde(rename = "BEC")]
    BEC,
    #[serde(rename = "BEL")]
    BEL,
    #[serde(rename = "BZD")]
    BZD,
    #[serde(rename = "BMD")]
    BMD,
    #[serde(rename = "BTN")]
    BTN,
    #[serde(rename = "BOB")]
    BOB,
    #[serde(rename = "BOL")]
    BOL,
    #[serde(rename = "BOV")]
    BOV,
    #[serde(rename = "BOP")]
    BOP,
    #[serde(rename = "BAM")]
    BAM,
    #[serde(rename = "BAD")]
    BAD,
    #[serde(rename = "BAN")]
    BAN,
    #[serde(rename = "BWP")]
    BWP,
    #[serde(rename = "BRC")]
    BRC,
    #[serde(rename = "BRZ")]
    BRZ,
    #[serde(rename = "BRE")]
    BRE,
    #[serde(rename = "BRR")]
    BRR,
    #[serde(rename = "BRN")]
    BRN,
    #[serde(rename = "BRB")]
    BRB,
    #[serde(rename = "BRL")]
    BRL,
    #[serde(rename = "GBP")]
    GBP,
    #[serde(rename = "BND")]
    BND,
    #[serde(rename = "BGL")]
    BGL,
    #[serde(rename = "BGN")]
    BGN,
    #[serde(rename = "BGO")]
    BGO,
    #[serde(rename = "BGM")]
    BGM,
    #[serde(rename = "BUK")]
    BUK,
    #[serde(rename = "BIF")]
    BIF,
    #[serde(rename = "XPF")]
    XPF,
    #[serde(rename = "KHR")]
    KHR,
    #[serde(rename = "CAD")]
    CAD,
    #[serde(rename = "CVE")]
    CVE,
    #[serde(rename = "KYD")]
    KYD,
    #[serde(rename = "XAF")]
    XAF,
    #[serde(rename = "CLE")]
    CLE,
    #[serde(rename = "CLP")]
    CLP,
    #[serde(rename = "CLF")]
    CLF,
    #[serde(rename = "CNX")]
    CNX,
    #[serde(rename = "CNY")]
    CNY,
    #[serde(rename = "CNH")]
    CNH,
    #[serde(rename = "COP")]
    COP,
    #[serde(rename = "COU")]
    COU,
    #[serde(rename = "KMF")]
    KMF,
    #[serde(rename = "CDF")]
    CDF,
    #[serde(rename = "CRC")]
    CRC,
    #[serde(rename = "HRD")]
    HRD,
    #[serde(rename = "HRK")]
    HRK,
    #[serde(rename = "CUC")]
    CUC,
    #[serde(rename = "CUP")]
    CUP,
    #[serde(rename = "CYP")]
    CYP,
    #[serde(rename = "CZK")]
    CZK,
    #[serde(rename = "CSK")]
    CSK,
    #[serde(rename = "DKK")]
    DKK,
    #[serde(rename = "DJF")]
    DJF,
    #[serde(rename = "DOP")]
    DOP,
    #[serde(rename = "NLG")]
    NLG,
    #[serde(rename = "XCD")]
    XCD,
    #[serde(rename = "DDM")]
    DDM,
    #[serde(rename = "ECS")]
    ECS,
    #[serde(rename = "ECV")]
    ECV,
    #[serde(rename = "EGP")]
    EGP,
    #[serde(rename = "GQE")]
    GQE,
    #[serde(rename = "ERN")]
    ERN,
    #[serde(rename = "EEK")]
    EEK,
    #[serde(rename = "ETB")]
    ETB,
    #[serde(rename = "EUR")]
    EUR,
    #[serde(rename = "XBA")]
    XBA,
    #[serde(rename = "XEU")]
    XEU,
    #[serde(rename = "XBB")]
    XBB,
    #[serde(rename = "XBC")]
    XBC,
    #[serde(rename = "XBD")]
    XBD,
    #[serde(rename = "FKP")]
    FKP,
    #[serde(rename = "FJD")]
    FJD,
    #[serde(rename = "FIM")]
    FIM,
    #[serde(rename = "FRF")]
    FRF,
    #[serde(rename = "XFO")]
    XFO,
    #[serde(rename = "XFU")]
    XFU,
    #[serde(rename = "GMD")]
    GMD,
    #[serde(rename = "GEK")]
    GEK,
    #[serde(rename = "GEL")]
    GEL,
    #[serde(rename = "DEM")]
    DEM,
    #[serde(rename = "GHS")]
    GHS,
    #[serde(rename = "GHC")]
    GHC,
    #[serde(rename = "GIP")]
    GIP,
    #[serde(rename = "XAU")]
    XAU,
    #[serde(rename = "GRD")]
    GRD,
    #[serde(rename = "GTQ")]
    GTQ,
    #[serde(rename = "GWP")]
    GWP,
    #[serde(rename = "GNF")]
    GNF,
    #[serde(rename = "GNS")]
    GNS,
    #[serde(rename = "GYD")]
    GYD,
    #[serde(rename = "HTG")]
    HTG,
    #[serde(rename = "HNL")]
    HNL,
    #[serde(rename = "HKD")]
    HKD,
    #[serde(rename = "HUF")]
    HUF,
    #[serde(rename = "IMP")]
    IMP,
    #[serde(rename = "ISK")]
    ISK,
    #[serde(rename = "ISJ")]
    ISJ,
    #[serde(rename = "INR")]
    INR,
    #[serde(rename = "IDR")]
    IDR,
    #[serde(rename = "IRR")]
    IRR,
    #[serde(rename = "IQD")]
    IQD,
    #[serde(rename = "IEP")]
    IEP,
    #[serde(rename = "ILS")]
    ILS,
    #[serde(rename = "ILP")]
    ILP,
    #[serde(rename = "ILR")]
    ILR,
    #[serde(rename = "ITL")]
    ITL,
    #[serde(rename = "JMD")]
    JMD,
    #[serde(rename = "JPY")]
    JPY,
    #[serde(rename = "JOD")]
    JOD,
    #[serde(rename = "KZT")]
    KZT,
    #[serde(rename = "KES")]
    KES,
    #[serde(rename = "KWD")]
    KWD,
    #[serde(rename = "KGS")]
    KGS,
    #[serde(rename = "LAK")]
    LAK,
    #[serde(rename = "LVL")]
    LVL,
    #[serde(rename = "LVR")]
    LVR,
    #[serde(rename = "LBP")]
    LBP,
    #[serde(rename = "LSL")]
    LSL,
    #[serde(rename = "LRD")]
    LRD,
    #[serde(rename = "LYD")]
    LYD,
    #[serde(rename = "LTL")]
    LTL,
    #[serde(rename = "LTT")]
    LTT,
    #[serde(rename = "LUL")]
    LUL,
    #[serde(rename = "LUC")]
    LUC,
    #[serde(rename = "LUF")]
    LUF,
    #[serde(rename = "MOP")]
    MOP,
    #[serde(rename = "MKD")]
    MKD,
    #[serde(rename = "MKN")]
    MKN,
    #[serde(rename = "MGA")]
    MGA,
    #[serde(rename = "MGF")]
    MGF,
    #[serde(rename = "MWK")]
    MWK,
    #[serde(rename = "MYR")]
    MYR,
    #[serde(rename = "MVR")]
    MVR,
    #[serde(rename = "MVP")]
    MVP,
    #[serde(rename = "MLF")]
    MLF,
    #[serde(rename = "MTL")]
    MTL,
    #[serde(rename = "MTP")]
    MTP,
    #[serde(rename = "MRU")]
    MRU,
    #[serde(rename = "MRO")]
    MRO,
    #[serde(rename = "MUR")]
    MUR,
    #[serde(rename = "MXV")]
    MXV,
    #[serde(rename = "MXN")]
    MXN,
    #[serde(rename = "MXP")]
    MXP,
    #[serde(rename = "MDC")]
    MDC,
    #[serde(rename = "MDL")]
    MDL,
    #[serde(rename = "MCF")]
    MCF,
    #[serde(rename = "MNT")]
    MNT,
    #[serde(rename = "MAD")]
    MAD,
    #[serde(rename = "MAF")]
    MAF,
    #[serde(rename = "MZE")]
    MZE,
    #[serde(rename = "MZN")]
    MZN,
    #[serde(rename = "MZM")]
    MZM,
    #[serde(rename = "MMK")]
    MMK,
    #[serde(rename = "NAD")]
    NAD,
    #[serde(rename = "NPR")]
    NPR,
    #[serde(rename = "ANG")]
    ANG,
    #[serde(rename = "TWD")]
    TWD,
    #[serde(rename = "NZD")]
    NZD,
    #[serde(rename = "NIO")]
    NIO,
    #[serde(rename = "NIC")]
    NIC,
    #[serde(rename = "NGN")]
    NGN,
    #[serde(rename = "KPW")]
    KPW,
    #[serde(rename = "NOK")]
    NOK,
    #[serde(rename = "OMR")]
    OMR,
    #[serde(rename = "PKR")]
    PKR,
    #[serde(rename = "XPD")]
    XPD,
    #[serde(rename = "PAB")]
    PAB,
    #[serde(rename = "PGK")]
    PGK,
    #[serde(rename = "PYG")]
    PYG,
    #[serde(rename = "PEI")]
    PEI,
    #[serde(rename = "PEN")]
    PEN,
    #[serde(rename = "PES")]
    PES,
    #[serde(rename = "PHP")]
    PHP,
    #[serde(rename = "XPT")]
    XPT,
    #[serde(rename = "PLN")]
    PLN,
    #[serde(rename = "PLZ")]
    PLZ,
    #[serde(rename = "PTE")]
    PTE,
    #[serde(rename = "GWE")]
    GWE,
    #[serde(rename = "QAR")]
    QAR,
    #[serde(rename = "XRE")]
    XRE,
    #[serde(rename = "RHD")]
    RHD,
    #[serde(rename = "RON")]
    RON,
    #[serde(rename = "ROL")]
    ROL,
    #[serde(rename = "RUB")]
    RUB,
    #[serde(rename = "RUR")]
    RUR,
    #[serde(rename = "RWF")]
    RWF,
    #[serde(rename = "SVC")]
    SVC,
    #[serde(rename = "WST")]
    WST,
    #[serde(rename = "SAR")]
    SAR,
    #[serde(rename = "RSD")]
    RSD,
    #[serde(rename = "CSD")]
    CSD,
    #[serde(rename = "SCR")]
    SCR,
    #[serde(rename = "SLL")]
    SLL,
    #[serde(rename = "XAG")]
    XAG,
    #[serde(rename = "SGD")]
    SGD,
    #[serde(rename = "SKK")]
    SKK,
    #[serde(rename = "SIT")]
    SIT,
    #[serde(rename = "SBD")]
    SBD,
    #[serde(rename = "SOS")]
    SOS,
    #[serde(rename = "ZAR")]
    ZAR,
    #[serde(rename = "ZAL")]
    ZAL,
    #[serde(rename = "KRH")]
    KRH,
    #[serde(rename = "KRW")]
    KRW,
    #[serde(rename = "KRO")]
    KRO,
    #[serde(rename = "SSP")]
    SSP,
    #[serde(rename = "SUR")]
    SUR,
    #[serde(rename = "ESP")]
    ESP,
    #[serde(rename = "ESA")]
    ESA,
    #[serde(rename = "ESB")]
    ESB,
    #[serde(rename = "XDR")]
    XDR,
    #[serde(rename = "LKR")]
    LKR,
    #[serde(rename = "SHP")]
    SHP,
    #[serde(rename = "XSU")]
    XSU,
    #[serde(rename = "SDD")]
    SDD,
    #[serde(rename = "SDG")]
    SDG,
    #[serde(rename = "SDP")]
    SDP,
    #[serde(rename = "SRD")]
    SRD,
    #[serde(rename = "SRG")]
    SRG,
    #[serde(rename = "SZL")]
    SZL,
    #[serde(rename = "SEK")]
    SEK,
    #[serde(rename = "CHF")]
    CHF,
    #[serde(rename = "SYP")]
    SYP,
    #[serde(rename = "STN")]
    STN,
    #[serde(rename = "STD")]
    STD,
    #[serde(rename = "TVD")]
    TVD,
    #[serde(rename = "TJR")]
    TJR,
    #[serde(rename = "TJS")]
    TJS,
    #[serde(rename = "TZS")]
    TZS,
    #[serde(rename = "XTS")]
    XTS,
    #[serde(rename = "THB")]
    THB,
    #[serde(rename = "XXX")]
    XXX,
    #[serde(rename = "TPE")]
    TPE,
    #[serde(rename = "TOP")]
    TOP,
    #[serde(rename = "TTD")]
    TTD,
    #[serde(rename = "TND")]
    TND,
    #[serde(rename = "TRY")]
    _TRY,
    #[serde(rename = "TRL")]
    TRL,
    #[serde(rename = "TMT")]
    TMT,
    #[serde(rename = "TMM")]
    TMM,
    #[serde(rename = "USD")]
    USD,
    #[serde(rename = "USN")]
    USN,
    #[serde(rename = "USS")]
    USS,
    #[serde(rename = "UGX")]
    UGX,
    #[serde(rename = "UGS")]
    UGS,
    #[serde(rename = "UAH")]
    UAH,
    #[serde(rename = "UAK")]
    UAK,
    #[serde(rename = "AED")]
    AED,
    #[serde(rename = "UYW")]
    UYW,
    #[serde(rename = "UYU")]
    UYU,
    #[serde(rename = "UYP")]
    UYP,
    #[serde(rename = "UYI")]
    UYI,
    #[serde(rename = "UZS")]
    UZS,
    #[serde(rename = "VUV")]
    VUV,
    #[serde(rename = "VES")]
    VES,
    #[serde(rename = "VEB")]
    VEB,
    #[serde(rename = "VEF")]
    VEF,
    #[serde(rename = "VND")]
    VND,
    #[serde(rename = "VNN")]
    VNN,
    #[serde(rename = "CHE")]
    CHE,
    #[serde(rename = "CHW")]
    CHW,
    #[serde(rename = "XOF")]
    XOF,
    #[serde(rename = "YDD")]
    YDD,
    #[serde(rename = "YER")]
    YER,
    #[serde(rename = "YUN")]
    YUN,
    #[serde(rename = "YUD")]
    YUD,
    #[serde(rename = "YUM")]
    YUM,
    #[serde(rename = "YUR")]
    YUR,
    #[serde(rename = "ZWN")]
    ZWN,
    #[serde(rename = "ZRN")]
    ZRN,
    #[serde(rename = "ZRZ")]
    ZRZ,
    #[serde(rename = "ZMW")]
    ZMW,
    #[serde(rename = "ZMK")]
    ZMK,
    #[serde(rename = "ZWD")]
    ZWD,
    #[serde(rename = "ZWR")]
    ZWR,
    #[serde(rename = "ZWL")]
    ZWL,

}

impl ToString for PayCurrencyEnum {
    fn to_string(&self) -> String {
        match self {
            Self::XUA => String::from("XUA"),
            Self::AFN => String::from("AFN"),
            Self::AFA => String::from("AFA"),
            Self::ALL => String::from("ALL"),
            Self::ALK => String::from("ALK"),
            Self::DZD => String::from("DZD"),
            Self::ADP => String::from("ADP"),
            Self::AOA => String::from("AOA"),
            Self::AOK => String::from("AOK"),
            Self::AON => String::from("AON"),
            Self::AOR => String::from("AOR"),
            Self::ARA => String::from("ARA"),
            Self::ARS => String::from("ARS"),
            Self::ARM => String::from("ARM"),
            Self::ARP => String::from("ARP"),
            Self::ARL => String::from("ARL"),
            Self::AMD => String::from("AMD"),
            Self::AWG => String::from("AWG"),
            Self::AUD => String::from("AUD"),
            Self::ATS => String::from("ATS"),
            Self::AZN => String::from("AZN"),
            Self::AZM => String::from("AZM"),
            Self::BSD => String::from("BSD"),
            Self::BHD => String::from("BHD"),
            Self::BDT => String::from("BDT"),
            Self::BBD => String::from("BBD"),
            Self::BYN => String::from("BYN"),
            Self::BYB => String::from("BYB"),
            Self::BYR => String::from("BYR"),
            Self::BEF => String::from("BEF"),
            Self::BEC => String::from("BEC"),
            Self::BEL => String::from("BEL"),
            Self::BZD => String::from("BZD"),
            Self::BMD => String::from("BMD"),
            Self::BTN => String::from("BTN"),
            Self::BOB => String::from("BOB"),
            Self::BOL => String::from("BOL"),
            Self::BOV => String::from("BOV"),
            Self::BOP => String::from("BOP"),
            Self::BAM => String::from("BAM"),
            Self::BAD => String::from("BAD"),
            Self::BAN => String::from("BAN"),
            Self::BWP => String::from("BWP"),
            Self::BRC => String::from("BRC"),
            Self::BRZ => String::from("BRZ"),
            Self::BRE => String::from("BRE"),
            Self::BRR => String::from("BRR"),
            Self::BRN => String::from("BRN"),
            Self::BRB => String::from("BRB"),
            Self::BRL => String::from("BRL"),
            Self::GBP => String::from("GBP"),
            Self::BND => String::from("BND"),
            Self::BGL => String::from("BGL"),
            Self::BGN => String::from("BGN"),
            Self::BGO => String::from("BGO"),
            Self::BGM => String::from("BGM"),
            Self::BUK => String::from("BUK"),
            Self::BIF => String::from("BIF"),
            Self::XPF => String::from("XPF"),
            Self::KHR => String::from("KHR"),
            Self::CAD => String::from("CAD"),
            Self::CVE => String::from("CVE"),
            Self::KYD => String::from("KYD"),
            Self::XAF => String::from("XAF"),
            Self::CLE => String::from("CLE"),
            Self::CLP => String::from("CLP"),
            Self::CLF => String::from("CLF"),
            Self::CNX => String::from("CNX"),
            Self::CNY => String::from("CNY"),
            Self::CNH => String::from("CNH"),
            Self::COP => String::from("COP"),
            Self::COU => String::from("COU"),
            Self::KMF => String::from("KMF"),
            Self::CDF => String::from("CDF"),
            Self::CRC => String::from("CRC"),
            Self::HRD => String::from("HRD"),
            Self::HRK => String::from("HRK"),
            Self::CUC => String::from("CUC"),
            Self::CUP => String::from("CUP"),
            Self::CYP => String::from("CYP"),
            Self::CZK => String::from("CZK"),
            Self::CSK => String::from("CSK"),
            Self::DKK => String::from("DKK"),
            Self::DJF => String::from("DJF"),
            Self::DOP => String::from("DOP"),
            Self::NLG => String::from("NLG"),
            Self::XCD => String::from("XCD"),
            Self::DDM => String::from("DDM"),
            Self::ECS => String::from("ECS"),
            Self::ECV => String::from("ECV"),
            Self::EGP => String::from("EGP"),
            Self::GQE => String::from("GQE"),
            Self::ERN => String::from("ERN"),
            Self::EEK => String::from("EEK"),
            Self::ETB => String::from("ETB"),
            Self::EUR => String::from("EUR"),
            Self::XBA => String::from("XBA"),
            Self::XEU => String::from("XEU"),
            Self::XBB => String::from("XBB"),
            Self::XBC => String::from("XBC"),
            Self::XBD => String::from("XBD"),
            Self::FKP => String::from("FKP"),
            Self::FJD => String::from("FJD"),
            Self::FIM => String::from("FIM"),
            Self::FRF => String::from("FRF"),
            Self::XFO => String::from("XFO"),
            Self::XFU => String::from("XFU"),
            Self::GMD => String::from("GMD"),
            Self::GEK => String::from("GEK"),
            Self::GEL => String::from("GEL"),
            Self::DEM => String::from("DEM"),
            Self::GHS => String::from("GHS"),
            Self::GHC => String::from("GHC"),
            Self::GIP => String::from("GIP"),
            Self::XAU => String::from("XAU"),
            Self::GRD => String::from("GRD"),
            Self::GTQ => String::from("GTQ"),
            Self::GWP => String::from("GWP"),
            Self::GNF => String::from("GNF"),
            Self::GNS => String::from("GNS"),
            Self::GYD => String::from("GYD"),
            Self::HTG => String::from("HTG"),
            Self::HNL => String::from("HNL"),
            Self::HKD => String::from("HKD"),
            Self::HUF => String::from("HUF"),
            Self::IMP => String::from("IMP"),
            Self::ISK => String::from("ISK"),
            Self::ISJ => String::from("ISJ"),
            Self::INR => String::from("INR"),
            Self::IDR => String::from("IDR"),
            Self::IRR => String::from("IRR"),
            Self::IQD => String::from("IQD"),
            Self::IEP => String::from("IEP"),
            Self::ILS => String::from("ILS"),
            Self::ILP => String::from("ILP"),
            Self::ILR => String::from("ILR"),
            Self::ITL => String::from("ITL"),
            Self::JMD => String::from("JMD"),
            Self::JPY => String::from("JPY"),
            Self::JOD => String::from("JOD"),
            Self::KZT => String::from("KZT"),
            Self::KES => String::from("KES"),
            Self::KWD => String::from("KWD"),
            Self::KGS => String::from("KGS"),
            Self::LAK => String::from("LAK"),
            Self::LVL => String::from("LVL"),
            Self::LVR => String::from("LVR"),
            Self::LBP => String::from("LBP"),
            Self::LSL => String::from("LSL"),
            Self::LRD => String::from("LRD"),
            Self::LYD => String::from("LYD"),
            Self::LTL => String::from("LTL"),
            Self::LTT => String::from("LTT"),
            Self::LUL => String::from("LUL"),
            Self::LUC => String::from("LUC"),
            Self::LUF => String::from("LUF"),
            Self::MOP => String::from("MOP"),
            Self::MKD => String::from("MKD"),
            Self::MKN => String::from("MKN"),
            Self::MGA => String::from("MGA"),
            Self::MGF => String::from("MGF"),
            Self::MWK => String::from("MWK"),
            Self::MYR => String::from("MYR"),
            Self::MVR => String::from("MVR"),
            Self::MVP => String::from("MVP"),
            Self::MLF => String::from("MLF"),
            Self::MTL => String::from("MTL"),
            Self::MTP => String::from("MTP"),
            Self::MRU => String::from("MRU"),
            Self::MRO => String::from("MRO"),
            Self::MUR => String::from("MUR"),
            Self::MXV => String::from("MXV"),
            Self::MXN => String::from("MXN"),
            Self::MXP => String::from("MXP"),
            Self::MDC => String::from("MDC"),
            Self::MDL => String::from("MDL"),
            Self::MCF => String::from("MCF"),
            Self::MNT => String::from("MNT"),
            Self::MAD => String::from("MAD"),
            Self::MAF => String::from("MAF"),
            Self::MZE => String::from("MZE"),
            Self::MZN => String::from("MZN"),
            Self::MZM => String::from("MZM"),
            Self::MMK => String::from("MMK"),
            Self::NAD => String::from("NAD"),
            Self::NPR => String::from("NPR"),
            Self::ANG => String::from("ANG"),
            Self::TWD => String::from("TWD"),
            Self::NZD => String::from("NZD"),
            Self::NIO => String::from("NIO"),
            Self::NIC => String::from("NIC"),
            Self::NGN => String::from("NGN"),
            Self::KPW => String::from("KPW"),
            Self::NOK => String::from("NOK"),
            Self::OMR => String::from("OMR"),
            Self::PKR => String::from("PKR"),
            Self::XPD => String::from("XPD"),
            Self::PAB => String::from("PAB"),
            Self::PGK => String::from("PGK"),
            Self::PYG => String::from("PYG"),
            Self::PEI => String::from("PEI"),
            Self::PEN => String::from("PEN"),
            Self::PES => String::from("PES"),
            Self::PHP => String::from("PHP"),
            Self::XPT => String::from("XPT"),
            Self::PLN => String::from("PLN"),
            Self::PLZ => String::from("PLZ"),
            Self::PTE => String::from("PTE"),
            Self::GWE => String::from("GWE"),
            Self::QAR => String::from("QAR"),
            Self::XRE => String::from("XRE"),
            Self::RHD => String::from("RHD"),
            Self::RON => String::from("RON"),
            Self::ROL => String::from("ROL"),
            Self::RUB => String::from("RUB"),
            Self::RUR => String::from("RUR"),
            Self::RWF => String::from("RWF"),
            Self::SVC => String::from("SVC"),
            Self::WST => String::from("WST"),
            Self::SAR => String::from("SAR"),
            Self::RSD => String::from("RSD"),
            Self::CSD => String::from("CSD"),
            Self::SCR => String::from("SCR"),
            Self::SLL => String::from("SLL"),
            Self::XAG => String::from("XAG"),
            Self::SGD => String::from("SGD"),
            Self::SKK => String::from("SKK"),
            Self::SIT => String::from("SIT"),
            Self::SBD => String::from("SBD"),
            Self::SOS => String::from("SOS"),
            Self::ZAR => String::from("ZAR"),
            Self::ZAL => String::from("ZAL"),
            Self::KRH => String::from("KRH"),
            Self::KRW => String::from("KRW"),
            Self::KRO => String::from("KRO"),
            Self::SSP => String::from("SSP"),
            Self::SUR => String::from("SUR"),
            Self::ESP => String::from("ESP"),
            Self::ESA => String::from("ESA"),
            Self::ESB => String::from("ESB"),
            Self::XDR => String::from("XDR"),
            Self::LKR => String::from("LKR"),
            Self::SHP => String::from("SHP"),
            Self::XSU => String::from("XSU"),
            Self::SDD => String::from("SDD"),
            Self::SDG => String::from("SDG"),
            Self::SDP => String::from("SDP"),
            Self::SRD => String::from("SRD"),
            Self::SRG => String::from("SRG"),
            Self::SZL => String::from("SZL"),
            Self::SEK => String::from("SEK"),
            Self::CHF => String::from("CHF"),
            Self::SYP => String::from("SYP"),
            Self::STN => String::from("STN"),
            Self::STD => String::from("STD"),
            Self::TVD => String::from("TVD"),
            Self::TJR => String::from("TJR"),
            Self::TJS => String::from("TJS"),
            Self::TZS => String::from("TZS"),
            Self::XTS => String::from("XTS"),
            Self::THB => String::from("THB"),
            Self::XXX => String::from("XXX"),
            Self::TPE => String::from("TPE"),
            Self::TOP => String::from("TOP"),
            Self::TTD => String::from("TTD"),
            Self::TND => String::from("TND"),
            Self::_TRY => String::from("TRY"),
            Self::TRL => String::from("TRL"),
            Self::TMT => String::from("TMT"),
            Self::TMM => String::from("TMM"),
            Self::USD => String::from("USD"),
            Self::USN => String::from("USN"),
            Self::USS => String::from("USS"),
            Self::UGX => String::from("UGX"),
            Self::UGS => String::from("UGS"),
            Self::UAH => String::from("UAH"),
            Self::UAK => String::from("UAK"),
            Self::AED => String::from("AED"),
            Self::UYW => String::from("UYW"),
            Self::UYU => String::from("UYU"),
            Self::UYP => String::from("UYP"),
            Self::UYI => String::from("UYI"),
            Self::UZS => String::from("UZS"),
            Self::VUV => String::from("VUV"),
            Self::VES => String::from("VES"),
            Self::VEB => String::from("VEB"),
            Self::VEF => String::from("VEF"),
            Self::VND => String::from("VND"),
            Self::VNN => String::from("VNN"),
            Self::CHE => String::from("CHE"),
            Self::CHW => String::from("CHW"),
            Self::XOF => String::from("XOF"),
            Self::YDD => String::from("YDD"),
            Self::YER => String::from("YER"),
            Self::YUN => String::from("YUN"),
            Self::YUD => String::from("YUD"),
            Self::YUM => String::from("YUM"),
            Self::YUR => String::from("YUR"),
            Self::ZWN => String::from("ZWN"),
            Self::ZRN => String::from("ZRN"),
            Self::ZRZ => String::from("ZRZ"),
            Self::ZMW => String::from("ZMW"),
            Self::ZMK => String::from("ZMK"),
            Self::ZWD => String::from("ZWD"),
            Self::ZWR => String::from("ZWR"),
            Self::ZWL => String::from("ZWL"),
        }
    }
}

impl Default for PayCurrencyEnum {
    fn default() -> PayCurrencyEnum {
        Self::XUA
    }
}




