/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayFrequencyEnum {
    #[serde(rename = "WEEKLY")]
    WEEKLY,
    #[serde(rename = "BIWEEKLY")]
    BIWEEKLY,
    #[serde(rename = "MONTHLY")]
    MONTHLY,
    #[serde(rename = "QUARTERLY")]
    QUARTERLY,
    #[serde(rename = "SEMIANNUALLY")]
    SEMIANNUALLY,
    #[serde(rename = "ANNUALLY")]
    ANNUALLY,
    #[serde(rename = "THIRTEEN-MONTHLY")]
    THIRTEENMONTHLY,
    #[serde(rename = "PRO_RATA")]
    PRORATA,
    #[serde(rename = "SEMIMONTHLY")]
    SEMIMONTHLY,

}

impl ToString for PayFrequencyEnum {
    fn to_string(&self) -> String {
        match self {
            Self::WEEKLY => String::from("WEEKLY"),
            Self::BIWEEKLY => String::from("BIWEEKLY"),
            Self::MONTHLY => String::from("MONTHLY"),
            Self::QUARTERLY => String::from("QUARTERLY"),
            Self::SEMIANNUALLY => String::from("SEMIANNUALLY"),
            Self::ANNUALLY => String::from("ANNUALLY"),
            Self::THIRTEENMONTHLY => String::from("THIRTEEN-MONTHLY"),
            Self::PRORATA => String::from("PRO_RATA"),
            Self::SEMIMONTHLY => String::from("SEMIMONTHLY"),
        }
    }
}

impl Default for PayFrequencyEnum {
    fn default() -> PayFrequencyEnum {
        Self::WEEKLY
    }
}




