/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReasonEnum {
    #[serde(rename = "GENERAL_CUSTOMER_REQUEST")]
    GENERALCUSTOMERREQUEST,
    #[serde(rename = "GDPR")]
    GDPR,
    #[serde(rename = "OTHER")]
    OTHER,

}

impl ToString for ReasonEnum {
    fn to_string(&self) -> String {
        match self {
            Self::GENERALCUSTOMERREQUEST => String::from("GENERAL_CUSTOMER_REQUEST"),
            Self::GDPR => String::from("GDPR"),
            Self::OTHER => String::from("OTHER"),
        }
    }
}

impl Default for ReasonEnum {
    fn default() -> ReasonEnum {
        Self::GENERALCUSTOMERREQUEST
    }
}




