/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */

/// RemoteKeyForRegenerationRequest : # The RemoteKeyForRegeneration Object ### Description The `RemoteKeyForRegeneration` object is used to exchange an old remote key for a new one  ### Usage Example Post a `RemoteKeyForRegeneration` to swap out an old remote key for a new one



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoteKeyForRegenerationRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl RemoteKeyForRegenerationRequest {
    /// # The RemoteKeyForRegeneration Object ### Description The `RemoteKeyForRegeneration` object is used to exchange an old remote key for a new one  ### Usage Example Post a `RemoteKeyForRegeneration` to swap out an old remote key for a new one
    pub fn new(name: String) -> RemoteKeyForRegenerationRequest {
        RemoteKeyForRegenerationRequest {
            name,
        }
    }
}


