/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */

/// RemoteResponse : # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemoteResponse {
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "response")]
    pub response: Option<serde_json::Value>,
    #[serde(rename = "response_headers", skip_serializing_if = "Option::is_none")]
    pub response_headers: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "response_type", skip_serializing_if = "Option::is_none")]
    pub response_type: Option<Box<crate::models::ResponseTypeEnum>>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl RemoteResponse {
    /// # The RemoteResponse Object ### Description The `RemoteResponse` object is used to represent information returned from a third-party endpoint.  ### Usage Example View the `RemoteResponse` returned from your `DataPassthrough`.
    pub fn new(method: String, path: String, status: i32, response: Option<serde_json::Value>) -> RemoteResponse {
        RemoteResponse {
            method,
            path,
            status,
            response,
            response_headers: None,
            response_type: None,
            headers: None,
        }
    }
}


