/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestTypeEnum {
    #[serde(rename = "VACATION")]
    VACATION,
    #[serde(rename = "SICK")]
    SICK,
    #[serde(rename = "PERSONAL")]
    PERSONAL,
    #[serde(rename = "JURY_DUTY")]
    JURYDUTY,
    #[serde(rename = "VOLUNTEER")]
    VOLUNTEER,
    #[serde(rename = "BEREAVEMENT")]
    BEREAVEMENT,

}

impl ToString for RequestTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::VACATION => String::from("VACATION"),
            Self::SICK => String::from("SICK"),
            Self::PERSONAL => String::from("PERSONAL"),
            Self::JURYDUTY => String::from("JURY_DUTY"),
            Self::VOLUNTEER => String::from("VOLUNTEER"),
            Self::BEREAVEMENT => String::from("BEREAVEMENT"),
        }
    }
}

impl Default for RequestTypeEnum {
    fn default() -> RequestTypeEnum {
        Self::VACATION
    }
}




