/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseTypeEnum {
    #[serde(rename = "JSON")]
    JSON,
    #[serde(rename = "BASE64_GZIP")]
    BASE64GZIP,

}

impl ToString for ResponseTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::JSON => String::from("JSON"),
            Self::BASE64GZIP => String::from("BASE64_GZIP"),
        }
    }
}

impl Default for ResponseTypeEnum {
    fn default() -> ResponseTypeEnum {
        Self::JSON
    }
}




