/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RunTypeEnum {
    #[serde(rename = "REGULAR")]
    REGULAR,
    #[serde(rename = "OFF_CYCLE")]
    OFFCYCLE,
    #[serde(rename = "CORRECTION")]
    CORRECTION,
    #[serde(rename = "TERMINATION")]
    TERMINATION,
    #[serde(rename = "SIGN_ON_BONUS")]
    SIGNONBONUS,

}

impl ToString for RunTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::REGULAR => String::from("REGULAR"),
            Self::OFFCYCLE => String::from("OFF_CYCLE"),
            Self::CORRECTION => String::from("CORRECTION"),
            Self::TERMINATION => String::from("TERMINATION"),
            Self::SIGNONBONUS => String::from("SIGN_ON_BONUS"),
        }
    }
}

impl Default for RunTypeEnum {
    fn default() -> RunTypeEnum {
        Self::REGULAR
    }
}




