/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelectiveSyncConfigurationsUsageEnum {
    #[serde(rename = "IN_NEXT_SYNC")]
    NEXTSYNC,
    #[serde(rename = "IN_LAST_SYNC")]
    LASTSYNC,

}

impl ToString for SelectiveSyncConfigurationsUsageEnum {
    fn to_string(&self) -> String {
        match self {
            Self::NEXTSYNC => String::from("IN_NEXT_SYNC"),
            Self::LASTSYNC => String::from("IN_LAST_SYNC"),
        }
    }
}

impl Default for SelectiveSyncConfigurationsUsageEnum {
    fn default() -> SelectiveSyncConfigurationsUsageEnum {
        Self::NEXTSYNC
    }
}




