/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncStatusStatusEnum {
    #[serde(rename = "SYNCING")]
    SYNCING,
    #[serde(rename = "DONE")]
    DONE,
    #[serde(rename = "FAILED")]
    FAILED,
    #[serde(rename = "DISABLED")]
    DISABLED,
    #[serde(rename = "PAUSED")]
    PAUSED,

}

impl ToString for SyncStatusStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::SYNCING => String::from("SYNCING"),
            Self::DONE => String::from("DONE"),
            Self::FAILED => String::from("FAILED"),
            Self::DISABLED => String::from("DISABLED"),
            Self::PAUSED => String::from("PAUSED"),
        }
    }
}

impl Default for SyncStatusStatusEnum {
    fn default() -> SyncStatusStatusEnum {
        Self::SYNCING
    }
}




