/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */

/// Tax : # The Tax Object ### Description The `Tax` object is used to represent a tax for a given employee's payroll run. One run could include several taxes.  ### Usage Example Fetch from the `LIST Taxes` endpoint and filter by `ID` to show all taxes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Tax {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "employee_payroll_run", skip_serializing_if = "Option::is_none")]
    pub employee_payroll_run: Option<String>,
    /// The tax's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The tax amount.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    /// Whether or not the employer is responsible for paying the tax.
    #[serde(rename = "employer_tax", skip_serializing_if = "Option::is_none")]
    pub employer_tax: Option<bool>,
    /// Indicates whether or not this object has been deleted by third party webhooks.
    #[serde(rename = "remote_was_deleted", skip_serializing_if = "Option::is_none")]
    pub remote_was_deleted: Option<bool>,
}

impl Tax {
    /// # The Tax Object ### Description The `Tax` object is used to represent a tax for a given employee's payroll run. One run could include several taxes.  ### Usage Example Fetch from the `LIST Taxes` endpoint and filter by `ID` to show all taxes.
    pub fn new() -> Tax {
        Tax {
            id: None,
            employee_payroll_run: None,
            name: None,
            amount: None,
            employer_tax: None,
            remote_was_deleted: None,
        }
    }
}


