/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationProblemSource {
    #[serde(rename = "pointer")]
    pub pointer: String,
}

impl ValidationProblemSource {
    pub fn new(pointer: String) -> ValidationProblemSource {
        ValidationProblemSource {
            pointer,
        }
    }
}


