/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebhookReceiver {
    #[serde(rename = "event")]
    pub event: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl WebhookReceiver {
    pub fn new(event: String, is_active: bool) -> WebhookReceiver {
        WebhookReceiver {
            event,
            is_active,
            key: None,
        }
    }
}


